# PostgreSQL. Versions 9.1 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("RAILS_DB_USERNAME") { 'root' }%>
  password: <%= ENV.fetch("RAILS_DB_PASSWORD") { '' }%>
  host: <%= ENV.fetch("RAILS_DB_HOST") { 'localhost' } %>
  port: 5432

development:
  <<: *default
  database: kaji_development

test:
  <<: *default
  database: kaji_test

production:
  <<: *default
  database: kaji_production
  username: kaji
  password: <%= ENV['KAJI_DATABASE_PASSWORD'] %>
